# Generated by Django 5.2 on 2025-04-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('reviews', '0002_alter_review_unique_together_alter_review_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='ads_reviews', to='reviews.review'),
        ),
    ]
