# Generated by Django 5.1.7 on 2025-04-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('vehicles', 'Транспорт'), ('real_estate', 'Недвижимость'), ('clothing', 'Одежда'), ('other', 'Другое')], default='other', max_length=50),
        ),
    ]
