# Generated by Django 5.1.7 on 2025-04-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='category',
        ),
    ]
