# Generated by Django 5.1.7 on 2025-04-23 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_remove_ad_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('vehicles', 'Транспорт'), ('real_estate', 'Недвижимость'), ('clothing', 'Одежда'), ('other', 'Другое')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
